/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sefianti_jni_KeyboardHook */

#ifndef _Included_com_sefianti_jni_KeyboardHook
#define _Included_com_sefianti_jni_KeyboardHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sefianti_jni_KeyboardHook
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sefianti_jni_KeyboardHook_init
  (JNIEnv *, jobject);

/*
 * Class:     com_sefianti_jni_KeyboardHook
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sefianti_jni_KeyboardHook_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
